# Kalman node
# ___________


# IMU driver : 1 is the heavy and 2 is heavy MKII
imu_version: 1

# Define the roll offset, based on the config of the IMU
# USMMA/SLB data: 180
# SUNY/ICRA: 90
# Newest vehicle: 90
imu_offset: 180

# Are we using the Gyro? True if there is the FOG sensor
use_gyro: False

# Variable used to manage the error due to high velocity
dvl_max_velocity: 0.5

# State vector : (x,y,z,roll, pitch, yaw, x_dot,y_dot,z_dot,roll_dot,pitch_dot,yaw_dot)
state_vector: [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]]

# Covariance matrix
cov_matrix: [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]
             
# Q is the Process Noise Uncertainty 
#Q: [[sigma_x, 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.    ], 
#    [0., sigma_y, 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.    ],
#    [0., 0., sigma_z, 0., 0., 0., 0., 0., 0., 0., 0., 0.    ],
#    [0., 0., 0., sigma_roll, 0., 0., 0., 0., 0., 0., 0., 0. ],
#    [0., 0., 0., 0., sigma_pitch, 0., 0., 0., 0., 0., 0., 0.],
#    [0., 0., 0., 0., 0., sigma_yaw, 0., 0., 0., 0., 0., 0.  ],
#    [0., 0., 0., 0., 0., 0., sigma_xd, 0., 0., 0., 0., 0.   ],
#    [0., 0., 0., 0., 0., 0., 0., sigma_yd, 0., 0., 0., 0.   ],
#    [0., 0., 0., 0., 0., 0., 0., 0., sigma_zd, 0., 0., 0.   ],
#    [0., 0., 0., 0., 0., 0., 0., 0., 0.,sigma_rolld, 0., 0. ],
#    [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,sigma_pitchd, 0.],
#    [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,sigma_yawd  ]] 
 
Q: [[0.0001, 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.  ], 
    [0., 0.01, 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.    ],
    [0., 0.,  0.01, 0., 0., 0., 0., 0., 0., 0., 0., 0.   ],
    [0., 0., 0., 0.1, 0., 0., 0., 0., 0., 0., 0., 0.     ],
    [0., 0., 0., 0., 0.0001, 0., 0., 0., 0., 0., 0., 0.  ],
    [0., 0., 0., 0., 0., 0.1, 0., 0., 0., 0., 0., 0.     ],
    [0., 0., 0., 0., 0., 0., 0.00015, 0., 0., 0., 0., 0. ],
    [0., 0., 0., 0., 0., 0., 0., 0.00009, 0., 0., 0., 0. ],
    [0., 0., 0., 0., 0., 0., 0., 0., 0.1, 0., 0., 0.     ],
    [0., 0., 0., 0., 0., 0., 0., 0., 0.,0.001, 0., 0.    ],
    [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,0.01, 0.     ],
    [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,0.01     ]]
    
    
# A is the State Transition Matrix
#A: [[1. , 0. , 0. , 0. , 0. , 0. , dt, 0. , 0. , 0. , 0. , 0.  ],
#    [0. , 1. , 0. , 0. , 0. , 0. , 0. , dt, 0. , 0. , 0. , 0.  ],
#    [0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
#    [0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , dt, 0. , 0.  ],
#    [0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , dt, 0.  ],
#    [0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. ],
#    [0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. ],
#    [0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. ],
#    [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. ],
#    [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. ],
#    [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. ],
#    [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. ]]

# We are using dt_imu since we're doing the prediction in imu_callback()
A_imu: [[1. , 0. , 0. , 0. , 0. , 0. ,0.005, 0. , 0. , 0. , 0. , 0.  ],
        [0. , 1. , 0. , 0. , 0. , 0. , 0. ,0.005, 0. , 0. , 0. , 0.  ],
        [0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. ,0.005, 0. , 0.  ],
        [0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. ,0.005, 0.  ],
        [0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. ]]
        

# DVL parameters -----------------------------------------------------
dt_dvl: 0.2 # 5Hz
R_dvl: [[0.0001,0., 0.], 
        [0.,0.0001, 0.],
        [0.,0.,  0.001]]
H_dvl: [[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,]]

# IMU parameters -----------------------------------------------------
dt_imu: 0.005 # 200Hz
R_imu: [[0.01,0., 0.],
        [0.,0.01,0.,],
        [0.,0., 0.01]]
H_imu: [[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]]

# Depth parameters ---------------------------------------------------
dt_depth: 0.25 #4Hz
R_depth: [[0.01,0.,0.],
          [0.,0.01,0.],
          [0.,0.,0.01]]
H_depth: [[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]

# Gyro parameters ----------------------------------------------------
dt_gyro: 0.004 # 250Hz
H_gyro: [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]
R_gyro: [[0.00000001,0., 0.],
         [0.,0.00000001, 0.],
         [0.,0., 0.00000001]]
  
         
# ---
# Offsets, the rotation offset between the gyro frame and sonar frame. 
# /!\ IN DEGREES 
offset:
  x: 0.
  y: 0.
  z: 45.


